### ISSUE TITLE
Character sheets  do not open/ throwing errors

### ISSUE THREAD

**Issue by LorduFreeman** [taragnor/city-of-mist#33]
Foundry V10 290
CoM 2.6.0

Error occurs both on an already existing and a newly created world:
Old world
```
TypeError: An error occurred while rendering CityCharacterSheet 32. Cannot read properties of undefined (reading 'id')
    at SceneTags.getSceneContainer (scene-tags.mjs:41:38)
    at CityCharacterSheet.getOtherStatuses (city-character-sheet.js:230:22)
    at CityCharacterSheet.getData (city-character-sheet.js:62:35)
    at async CityCharacterSheet._render (foundry.js:5067:18)
    at async CityCharacterSheet._render (foundry.js:5780:5)
```
New World (no modules, freshly created)
```
foundry.js:747 TypeError: An error occurred while rendering CityCharacterSheet 35. Cannot read properties of undefined (reading 'id')
    at SceneTags.getSceneContainer (scene-tags.mjs:41:38)
    at CityCharacterSheet.getOtherStatuses (city-character-sheet.js:230:22)
    at CityCharacterSheet.getData (city-character-sheet.js:62:35)
    at async CityCharacterSheet._render (foundry.js:5067:18)
    at async CityCharacterSheet._render (foundry.js:5780:5)
```

Edit: On the new world, this happened because no scene was created (active) - probably because of the new scene container feature.

On the old world I can only guess, but it seems that only logging in as a player after migration doesn't trigger the necessary changes/scene activation for the container either? 
```
Uncaught (in promise) Error: User XXX lacks permission to create Setting [UeGMDPRRRib1Syfu]
    at ServerDatabaseBackend._createDocuments (/home/ubuntu/foundry/resources/app/dist/database/backend/server-backend.mjs:1:2047)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Semaphore._try (/home/ubuntu/foundry/resources/app/common/utils/semaphore.mjs:101:17)
```

**Comment by taragnor** [comment]
The new world bug I'm aware of. It can be fixed by just creating a scene and making sure there's an active scene. That should correct any bugs there. That should be fixed next release. In the meantime just create a scene and make it active and it should work fine. 

The second error on an established world I'm not sure of though, I haven't encountered that at all. What circumstances caused that? And does it happen for all players? And does it have a noticeable effect to the system loading/working?
