### ISSUE TITLE
Names for new themes and Mistery info are not saving in Player Card

### ISSUE THREAD

**Issue by Kirasna** [taragnor/city-of-mist#37]
Foundry version: 10, 291
City of Mist: 2.6.2
Active Modules: 0

When I edit player card and try to add new Theme, then give a Theme name it doesn't save. It changes back to "Unnamed Theme" and I get an error in the console:

city-actor-sheet.js:152 Uncaught (in promise) TypeError: actor.getTheme is not a function
    at CityCharacterSheet._themebookNameInput (city-actor-sheet.js:152:29)
    at HTMLTextAreaElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
    at Object.trigger (jquery.min.js:2:71659)
    at Object.simulate (jquery.min.js:2:72162)
    at HTMLDocument.i (jquery.min.js:2:72451)
city-actor-sheet.js:152 Uncaught (in promise) TypeError: actor.getTheme is not a function
    at CityCharacterSheet._themebookNameInput (city-actor-sheet.js:152:29)
    at HTMLTextAreaElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
_themebookNameInput @ city-actor-sheet.js:152
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
city-actor-sheet.js:152 Uncaught (in promise) TypeError: actor.getTheme is not a function
    at CityCharacterSheet._themebookNameInput (city-actor-sheet.js:152:29)
    at HTMLTextAreaElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
    at Object.trigger (jquery.min.js:2:71659)
    at Object.simulate (jquery.min.js:2:72162)
    at HTMLDocument.i (jquery.min.js:2:72451)
_themebookNameInput @ city-actor-sheet.js:152
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
simulate @ jquery.min.js:2
i @ jquery.min.js:2
city-actor-sheet.js:152 Uncaught (in promise) TypeError: actor.getTheme is not a function
    at CityCharacterSheet._themebookNameInput (city-actor-sheet.js:152:29)
    at HTMLTextAreaElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
_themebookNameInput @ city-actor-sheet.js:152
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
6city-actor-sheet.js:152 Uncaught (in promise) TypeError: actor.getTheme is not a function
    at CityCharacterSheet._themebookNameInput (city-actor-sheet.js:152:29)
    at HTMLTextAreaElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
    at Object.trigger (jquery.min.js:2:71659)
    at Object.simulate (jquery.min.js:2:72162)
    at HTMLDocument.i (jquery.min.js:2:72451)

The same problem when I try to add someting uder Mistery:
city-actor-sheet.js:143 Uncaught (in promise) TypeError: actor.getTheme is not a function
    at CityCharacterSheet._themeChangeInput (city-actor-sheet.js:143:29)
    at HTMLTextAreaElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

<img width="1591" alt="error" src="https://user-images.githubusercontent.com/9109286/210179378-74c5f4ed-819c-4fb9-bb06-4b24775668b7.PNG">

**Comment by taragnor** [comment]
This should be fixed in version 2.6.3
